1次提出（1/21）
kasai-suika/OJT-App pull request #1
Opened 2021-01-21 14:21 UTC by kasai-suika

■エラー内容
①リスト押下するも詳細画面へ遷移しない
　・関係のあるクラス：`LogFragment.java`、`LogAdapter.java`
　・エラー文はでない。
　・リストを押下しても`LogFragment.java#onItemClick()`内に移動しない。（＝onItemClick()内のログが出力されない）
　・レイアウトファイルと紐づけた`listtView`変数は中身が入っている。（＝LogFragment.java 60行目のログに出力される。）
　・listtView変数は`fragment_log.xml`の`ListView`と紐づいている。

②リスト内の編集ボタン押下でエラー
　※②はしっかりエラー見れていないため無視してください

2021-01-31 07:48 UTC, kasai-suika commented
今回の修正内容。
問題①：データ追加時にエラーになる。【解決】
　→String型からint型にうまく変換されていないことが原因でした。
　（未入力の際データなし=空文字のため、`Integer.parseInt(空文字)` でエラーが起きていました。）
　　DBでint型で保存されるべきデータが未入力の際は、-1（変数：NO_DATA）を代入することで、
　「本数」「地名」「ポイント名」以外は未入力でもデータ追加できるようにしました。

問題②：リスト押下できない【解決】
　→リストアイテムのレイアウトを構成しているルートに以下を設定しました。
　　 `android:descendantFocusability="blocksDescendants"`


今のところ「リスト画面、追加画面、詳細画面、削除ダイアログ」にエラーはみられません。
次はテストの作成＋コードを整理していきます。

2021-02-07 08:21 UTC, kasai-suika commented
■エラー内容
・削除時にエラー
　エラー文：
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
  
　エラー箇所：DialogFragmentクラスの` Intent intent = new Intent(getContext(), MainActivity.class);  `
　`public void onDeleted(boolean result) {  `
　　　　` Intent intent = new Intent(getContext(), MainActivity.class);  ` ☆
　　　　 ` intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);  `
　　　　 ` startActivity(intent);  `
　`  }  `

　削除は詳細画面と編集画面でできますが、正常に削除できる時と上記のエラーが出る時でまちまちです。

2021-02-07 14:28 UTC, kasai-suika commented
■エラー内容
・削除時にエラー
　エラー文：
 java.lang.IllegalStateException: Fragment DeleteDialogFragment{96161d1 (a588b1d5-e27a-4ac0-9898-e4059144d84d)} not attached to Activity
  
　エラー箇所：DialogFragmentクラス# onDeleted()#` startActivity(intent); `
　`public void onDeleted(boolean result) {  `
　　　　` Intent intent = new Intent(DeleteDialogFragment.this.context, MainActivity.class);  ` 
　　　　 ` intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);  `
　　　　 ` startActivity(intent);  `☆
　`  }  `

■確認したこと
　・現在表示しているActivityを調べたところ`LogActivity`でした。
　・`DeleteDialogFragment.this.context`は、DeleteDialogFragmentを呼び出したFragmentのcontextです。
　　（LogEditFragment と LogDetailFragment）
　・`DeleteDialogFragment.this.context`にはLogActivityが入っていました。
　　（`DeleteDialogFragment.this.context ＝ com.ojtapp.divinglog.view.detail.LogActivity@6ba4bff`）
  
現在のActivityを渡せているように見えるのですが、エラー文で` not attached to Activity`と出てしまい、手詰まりです。
お手すきの際にでも何かアドバイス頂ければと思います。よろしくお願いいたします。

2021-02-10 10:24 UTC, u1tramarinet requested changes

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/controller/DeleteAsyncTask.java
> +        db.delete(LogConstant.TABLE_NAME, selection, selectionArgs);
deleteの実行結果（成否）は特に返さなくてもよさそうですか？

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/controller/UpdateAsyncTask.java
> +        void onUpdate(boolean result);
これは正直好みもあるのですが、成功した時と失敗した時のCallbackメソッドは分けた方がよいと思います。（下記イメージ）

Callback受ける側の処理もbooleanでのif文ではなく、Callbackメソッドごとに処理が書けるので見やすかったり、例えば今後失敗した時の理由をいくつか用意することになった時に、失敗した時のCallbackメソッドの引数だけ拡張すれば対応できたりするからです。

```
public interface Callback {
      void onSuccess();
      void onFailure();
}
```

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/controller/WriteAsyncTask.java
> +    public WriteAsyncTask(@NonNull Context context){
クラスのネーミングが若干DB寄りになってきている感じしますね。

スタンス次第ですが、実際の処理を体現する名前よりかは、どのような時（ユースケース）に使うAsyncTaskなのかが分かるクラス名の方がよかったりもします。
このAsyncTaskを使うUI層に、内部でDBを使っていることを意識させない的な。

あくまで命名なので、これを戻したからと言って処理が変わるわけではないですが、初めて見た人が、「これはログを登録する時に使えるAsyncTaskなんだ」と把握しやすくなるかな、と思います。（このコメントを参考にするかは、正直お任せします...）

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +    public DeleteDialogFragment(Context context) {
DialogとはいえFragmentではあるので、コンストラクタは引数無しのものを使ってほしいです。レアケースですが、ダイアログ表示中に画面回転するとこのダイアログ再生成できなくなります。

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +        args.putSerializable(LogActivity.TABLE_KEY, divingLog);
このKeyはあくまでこのFragment内部でだけ共有されていればいい情報なので、Fragment内部でprivateで定義しましょう。

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +                startActivity(intent);
削除処理中は画面に何か「削除中」みたいな表示は出す予定ありますでしょうか？

多分そんな時間かからないので実装してもほぼ見える機会ない気はしますが、余裕があれば、削除中に「削除中」表示をするようにしてみましょう

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +        String className = activityManager.getRunningTasks(1).get(0).topActivity.getClassName();
個人的には、ダイアログの役割は最小限にした方がよいと考えています。「ユーザーに削除するか問うて、選択結果を元のFragmentに返すだけ」「実際の削除要求や削除中表示は元のFragmentで行う」

ただ多分、このダイアログを表示する"元のFragment"が２つあるので、ダイアログの役割を最低限にすると削除処理諸々が分散しそうですね...
（"個人的には"なので、そっちの方がよさそうって思ったら採用するくらいで大丈夫です）

※余談ですが、別の考え方も書いておきます。

ダイアログの役割をもっと最小限化・再利用性を高めて削除以外の機会でも使えるようにする方針もあります。ダイアログをただ渡された質問文とYes Noを表示して、Yes Noどっちが選択されたのかを元のFragmentに返すだけのものにする。そうすると今後例えば、写真を追加する時の確認ダイアログをクラス追加なしで実現できたりします。

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogActivity.java
> +                targetFragment = LogAddFragment.newInstance();
表示するFragmentを変える度にstartActivityはコストが高いのかもしれませんね
まず、下記を参考に、FragmentからActivityに対して要求して、実際の画面遷移はActivityで行うように、できればしたいですね

https://developer.android.com/training/basics/fragments/communicating?hl=ja

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogAddFragment.java
> +    private TimePicker timeEnd;
これは余裕があればですが、一定のセクションごとにCustomViewを作って、別クラスでそれぞれView群の管理をしたいですね。

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogDetailFragment.java
> +
Mustではないですが、たとえ使わなくても引数なしのコンストラクタは空で定義しておいた方が、間違いなくてよいです。

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogDetailFragment.java
> +            memo.setText(divingLog.getMemo());
中級者編ですが、DataBindingを使えば、このようなViewとデータの紐づけ作業がXMLで済むようになります。

https://developer.android.com/topic/libraries/data-binding?hl=ja

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogEditFragment.java
> +            String[] startTime = divingLog.getTimeStart().split(SEPARATE_TIME, 0);
ここら辺の日付の変換はSimpleDateFormatとかCalendarとか使って実現できるよより良いですね

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogEditFragment.java
> +                if ((LogAddFragment.NO_DATA == airStartInt) || (LogAddFragment.NO_DATA == airEndInt)) {
そのintがno_dataかどうかは別のboolean変数で持っておくとよいかもしれませんね。

Integer.MIN_VALUEとかやれば、避けられるのかもしれないですけど、変数ごとにどの値だったら回避できるのかをいちいち判断しなきゃいけないのが、もっと複雑なデータになってくると出てきそうですし

2021-02-10 10:24 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/LogAdapter.java
> +                context.startActivity(intent);
画面遷移処理はあまりAdapterに載せない方がよいです。Adapter自体はUI部品ではないので。（あくまでリストとデータの調整役）

Callbackを設けて、Adapterを使うFragmentやActivity側で画面遷移処理をやりたいですね

2021-02-12 18:10 UTC, kasai-suika commented
コメントいただいたものにまだ対応できていないのですが、1回目の提出をさせていただきます。
コメントいただいたものは順次手を付けていく予定です。

■内容
・リスト画面　　　・削除ダイアログ
・詳細画面　　　　・テスト（UI＋DB）
・編集画面

※削除系のテストは環境ゆえなのか上手くいかないので、Android携帯をお借りしてから作成します。

2021-02-12 18:13 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/controller/WriteAsyncTask.java
> +    public WriteAsyncTask(@NonNull Context context){
名前を以前のものにもどしました。

DB寄りの方がいいのかと逆を考えてしまっていたので、教えてくださってありがとうございます！
「どのような時（ユースケース）に使うAsyncTaskなのかが分かるクラス名」の方がいいのですね。

2021-02-12 18:14 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +    public DeleteDialogFragment(Context context) {
コンストラクタの引数をなくしました。
この指摘Todoアプリでもいただいた気が…
すっかり忘れていたので、見直しておきます。

2021-02-21 15:07 UTC, kasai-suika commented
写真をデータベースから取り出す際に下記のエラーが出てしまい詰まってしまいました。
中々解決策が見つけられないので、アドバイスいただけましたら幸いです。

・エラー文
```
Caused by: android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
```

・エラー文出現箇所
　DisplayAsyncTask#103行目　 while (cursor.moveToNext()) 　
　※DBからデータを取得しDivingLogクラスに詰めるクラスです。
　※保存処理時にBitmap型をbyte[]型に変更していますが、変更自体は正常にできていました。

・写真をDBに保存する型
　BLOB
　※UriやファイルパスをStringで保存しない理由は、DB以外のファイル操作で画像が削除された際に
　エラーにしたくないと考えたためです

2021-03-05 16:37 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/controller/DeleteAsyncTask.java
> +        db.delete(LogConstant.TABLE_NAME, selection, selectionArgs);
`return true`　とは別に返すということでしょうか？  
（そもそも`return true` は成否帰ってることになっていない…みたいな…？）

2021-03-05 16:41 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/controller/UpdateAsyncTask.java
> +        void onUpdate(boolean result);
AysncTAskのクラスで、成功時と失敗時のコールバックメソッドを分けました。
とても分かりやすいですね！！  

どちらを実行するかの判定は、AsyncTaskの` onPostExecute()`の引数がtrueだったら`onSuccess()`としていますが、
上のコメントを見ると`doInBackground()`でのreturnは現在成否判定になっていないのか？？となっています

2021-03-05 16:43 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/controller/DeleteAsyncTask.java
> +        db.delete(LogConstant.TABLE_NAME, selection, selectionArgs);
return true　とは別に返すということでしょうか？
（そもそもreturn true は成否帰ってることになっていない…みたいな…？）

2021-03-05 16:49 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +        args.putSerializable(LogActivity.TABLE_KEY, divingLog);
Activityで定義査定たものを、Fragment内部でprivateで定義するように変更しました。

2021-03-05 17:24 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogDetailFragment.java
> +
各フラグメントにデフォルトコンストラクタを定義しました。  
（デフォルトコンストラクタなるものの存在をすっかり忘れていました。）

2021-03-05 17:25 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogDetailFragment.java
> +            memo.setText(divingLog.getMemo());
（未対応）

2021-03-05 17:25 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogEditFragment.java
> +            String[] startTime = divingLog.getTimeStart().split(SEPARATE_TIME, 0);
（未対応）

2021-03-05 17:25 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogEditFragment.java
> +                if ((LogAddFragment.NO_DATA == airStartInt) || (LogAddFragment.NO_DATA == airEndInt)) {
（未対応）

2021-03-05 17:26 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/main/LogAdapter.java
> +                context.startActivity(intent);
（未対応）

2021-03-05 17:36 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +                startActivity(intent);
（未対応）

2021-03-05 17:36 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +        String className = activityManager.getRunningTasks(1).get(0).topActivity.getClassName();
（未対応）

2021-03-05 17:36 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogActivity.java
> +                targetFragment = LogAddFragment.newInstance();
（未対応）

2021-03-05 17:37 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogAddFragment.java
> +    private TimePicker timeEnd;
（未対応）

2021-03-05 17:40 UTC, kasai-suika commented
■変更内容
　・写真追加処理（マニフェストでの設定が結局わからなかったので、写真選択時にuriの権限保存の設定を追加しました。）
　・ソート処理
　・コメントいただいた内容の修正
　
1つのコミットに色々ぐちゃぐちゃに混じってしまいました。すみません。
現在未対応のコメントも順次対応予定です。

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +    private static final int INDEX1 = 1;
定数化するのであれば、定数名に意味を持たせた方がよいと思います。例えば、1個目（index=0）のデータセットは各入力値の最大値を試すものであれば、`INDEX_DATESET_MAX_VALUE`とか。（※あくまでパッと思いついた例です）逆に特に意味はなく、単なるバリエーションとして２つ用意しているのであれば、定数化せず直値でもよいと思います。

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +    int dataPosition;
この変数をpackage-privateにしているのは意図通りですか？

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +        final Context context = InstrumentationRegistry.getInstrumentation().getTargetContext();
もし今後テストケース（メソッド）が増えるのであれば、共通化できるところはしたいですね。contextの作り方が変わった時に各メソッドをそれぞれ修正する必要が出てきます。（Mustではないですが）

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +        final boolean[] flag = {false};
このflagは今後使用予定ものですしょうか？予定なければ削除しておきましょう

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +        setDataToDivingLog(divingLogs[0], INDEX0);  // 指定した要素の定数値をDivingLogクラスに設定
これは好みかもしれませんが、自分だったら`setDataToDivingLog()`の代わりに、`DivingLog`を返り値とした`getDivingLog()`を作成して、newしているところをそのメソッドに差し替えて一行で済ましますね

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +    public void getDataFromDB() throws InterruptedException {
１つのメソッドで「追加する」と「取得する」をセットでテストしている感じですかね。追加して取得してみることで、追加できて取得もできてる、みたいな感じで。もしそうであれば、メソッド名からわかるようにするとよいと思います。

ほかの人が見たときに処理を見ないと何を試験しているか分からないと、今後変更が発生した時にメンテや運用がし辛くなります。（とりあえず全部実施する、としても結局getだけ試験したんだっけ？となりそう）

少し経ってこのコードを書いたことを忘れた自分がこれを理解できるか、の観点でみるとよいです。

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +        getDataFromDB();    // DivingLogクラスをDBに保存し取得する。divingLogs[1]にはDBに最後に保存したデータが入っている。
テストメソッドからテストメソッドを呼ぶのであれば、共通の処理としてprivateメソッドで共通化しましょう

テストコードはテストしたいことやユースケースによって処理も変わったりします。その際、他のテストメソッドからも呼ばれていること・活用されていることを意識しなければいけません。そうすると、拡張や仕様変更がしづらくなります。

各メソッドが呼ばれるユースケースや経路は整理した方が、試験や仕様変更がしやすくなります。考慮することが減ってシンプルになるからです。

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +                        divingLogs[1] = logList.get(dataPosition);  // getDataFromDB() で取得したデータの場所と同じ場所にあるデータを取得
`dataPosition`を保持しておく意味は何でしょうか？コメントの通り、listの最後のデータを取得（`logList.get(logList.size() - 1)`）ではダメなのでしょうか？

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +public class DataBaseTest {
このDBテストは「取得（=getDataFromDB()）」と「追加（=updateDataInDB()）」の試験をしているものという理解であっていますでしょうか？「削除」や「更新」の試験は追加予定ありますか？

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/view/main/UITest.java
> +        textView3.check(matches(withText("日付")));
ここだけじゃないかもですが、同じ処理をしているところはメソッド化して、メソッド名を工夫すればもっと見やすくなりそうですね

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/androidTest/java/com/ojtapp/divinglog/view/main/UITest.java
> +        textView3.check(matches(withText("日付")));
同じ文字列を２回書いているのも、メソッド化することで一回で済みそう。コピペミスとか人的ミスも防ぎやすい

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/controller/DeleteAsyncTask.java
> +        db.delete(LogConstant.TABLE_NAME, selection, selectionArgs);
はい。成否は帰っていることにはなってます。現状、`db.delete`の結果がどうあれ、一律trueを返していると思います。例えば、`db.delete()`の失敗時などで`false`を返す必要があるケースがないか、の確認です。無ければ無いで問題ないです。

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/appif/DivingLog.java
> +    public void setPictureUri(String pictureUri) {
引数に`@NonNull`か``@Nullable`をつけましょう

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/SortMenu.java
> +        SortModes sortMode = SortModes.values()[sortModeValue];
sotrModeのindex数以上の値が指定された時のエラーハンドリングをしましょう

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/SortMenu.java
> +            return list.toArray(new String[0]);
正直この規模だとあまり差はでないですが、性能的には、list.toArray(new String[`list.size()`]);で書いた方がよさそう

http://yoonchulkoh.hatenablog.com/entry/20091006/1254841067

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/controller/DeleteAsyncTask.java
> +        db.delete(LogConstant.TABLE_NAME, selection, selectionArgs);
例えば、引数で渡ってきた`drivingLogs`のサイズが0だった（何も渡されてこなかった）時とか（まあ自分で全て実装している段階なので、書きようがないと思いますが）

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/util/SharedPreferencesUtil.java
> +        return sharedPreferences.getInt(key, SORT_MODE_DEFAULT_POSITION);
`getKey`と言いつつ、デフォルト値を見る限りSortMode専用のメソッドですかね。汎用的な名前のメソッドが実は特定の条件を持っていると、後々混乱の元になるので、分かるように変えたいですね

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +;
不要な記載は削除しましょう

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogAddFragment.java
> +    private void setDateToDivingLog(@NonNull DivingLog divingLog) {
`Date`は`Data`の誤記ですかね？

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogAddFragment.java
> +    public static int getIntData(@NonNull String strData) {
これはLogAddFragmentが公開すべき機能でしょうか？複数Fragmentで使用するのであれば、Util化しましょう

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogDetailFragment.java
> +
Fragmentのデフォルトコンストラクタは、publicじゃないといけないような記憶があるのですが、publicじゃなくても大丈夫そうですか？

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogDetailFragment.java
> +    public static String createStringData(int intData) {
これも、LogDetailFragment特有の機能ではなければ、Util化して共通化しましょう

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogEditFragment.java
> +        parcelFileDescriptor.close();
他のクラスでも同じような処理を見かけましたが、共通化できなさそうですか？共通化する場合、BitmapのUtilにまとまるイメージです

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/detail/SortDialogFragment.java
> +public class SortDialogFragment extends DialogFragment {
デフォルトコンストラクタがなさそう

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
>      public static final String TAG = MainActivity.class.getSimpleName();
TAGを他のクラスと共有して使ってます？

2021-03-07 17:18 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +    public static SharedPreferencesUtil sharedPreferencesUtil;
Utilクラスは一般的にはインスタンス化しない、staticなメソッドや定数のみで構成されているクラスです。もし、インスタンス化して管理したい場合は、utilではないものにしましょう

https://www.sgnet.co.jp/technology/java/java02_01/

2021-03-24 14:18 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/controller/DeleteAsyncTask.java
> +        db.delete(LogConstant.TABLE_NAME, selection, selectionArgs);
なるほど！ご回答ありがとうございます。  
AsyncTaskすべてに実行結果のreturnを追加しました。  
コミット名「AsyncTaskの実行結果（失敗時）のreturnを追加」に入っています。

2021-04-04 11:59 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +                startActivity(intent);
コミット名「削除処理中に「実行中...」と表示するダイアログを追加」内に修正を入れました。  
処理時間が一瞬でダイアログが見えなかったので、削除処理スレッドを2秒間sleepすることで見えるようにしました。

2021-05-06 07:55 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogActivity.java
> +                targetFragment = LogAddFragment.newInstance();
コミット「Fragment遷移をMainActivityで行い、LogActivityを削除」で対応しました。

2021-05-06 08:02 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogDetailFragment.java
> +
その通りでした。失礼いたしました。  
コミット「Fragmentのデフォルトコンストラクタをpublicに修正」にて対応いたしました。

2021-05-06 09:06 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +        String className = activityManager.getRunningTasks(1).get(0).topActivity.getClassName();
選択結果を元のフラグメントに返すだけに機能を限定するよう変更しました。  
実際の動作は各フラグメントで定義しています。  
コミット「ダイアログを削除専用ではなく普遍的なものに変更」にて対応いたしました。

2021-05-09 08:50 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogDetailFragment.java
> +            memo.setText(divingLog.getMemo());
（バインディングクラスが自動生成されないところから進まないため、いったん保留しています。）

2021-05-09 13:48 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +    private static final int INDEX1 = 1;
>定数化するのであれば、定数名に意味を持たせた方がよいと思います。  
>単なるバリエーションとして２つ用意しているのであれば、定数化せず直値でもよいと思います。  

承知いたしました。ありがとうございます。
テストの関しては作成したユースケースに従って作り直していこうと思いますのでクラス単位で
大きく内容が変わる予定です。   
レビューいただいた場所と大きく変わると思うのですが、内容を反映させていただきながら作成します。

2021-05-09 13:50 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +    int dataPosition;
下記の通りです。  
https://github.com/kasai-suika/OJT-App/pull/1#discussion_r628893149

2021-05-09 13:51 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +        final Context context = InstrumentationRegistry.getInstrumentation().getTargetContext();
下記の通りです。  
https://github.com/kasai-suika/OJT-App/pull/1#discussion_r628893149

2021-05-09 13:51 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +        final boolean[] flag = {false};
下記の通りです。  
https://github.com/kasai-suika/OJT-App/pull/1#discussion_r628893149

2021-05-09 13:51 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +        setDataToDivingLog(divingLogs[0], INDEX0);  // 指定した要素の定数値をDivingLogクラスに設定
下記の通りです。  
https://github.com/kasai-suika/OJT-App/pull/1#discussion_r628893149

2021-05-09 13:51 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +    public void getDataFromDB() throws InterruptedException {
下記の通りです。  
https://github.com/kasai-suika/OJT-App/pull/1#discussion_r628893149

2021-05-09 13:51 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +        getDataFromDB();    // DivingLogクラスをDBに保存し取得する。divingLogs[1]にはDBに最後に保存したデータが入っている。
下記の通りです。  
https://github.com/kasai-suika/OJT-App/pull/1#discussion_r628893149

2021-05-09 13:52 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +                        divingLogs[1] = logList.get(dataPosition);  // getDataFromDB() で取得したデータの場所と同じ場所にあるデータを取得
下記の通りです。  
https://github.com/kasai-suika/OJT-App/pull/1#discussion_r628893149

2021-05-09 13:52 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/DataBaseTest.java
> +public class DataBaseTest {
下記の通りです。  
https://github.com/kasai-suika/OJT-App/pull/1#discussion_r628893149

2021-05-09 13:52 UTC, kasai-suika commented on app/src/androidTest/java/com/ojtapp/divinglog/view/main/UITest.java
> +        textView3.check(matches(withText("日付")));
下記の通りです。  
https://github.com/kasai-suika/OJT-App/pull/1#discussion_r628893149

2021-05-09 14:09 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/appif/DivingLog.java
> +    public void setPictureUri(String pictureUri) {
すみません！  
コミット「 写真の未追加でエラーが出ないように変更＋各メソッドの@NonNull,@Nullable表記を追加」にて対応いたしました。

2021-05-09 14:21 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/SortMenu.java
> +        SortModes sortMode = SortModes.values()[sortModeValue];
コミット「sotrModeのindex数以上の値が指定された時のエラーハンドリングを追加」にて対応いたしました。

2021-05-09 14:34 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/SortMenu.java
> +            return list.toArray(new String[0]);
なるほど余分にオブジェクト作成していたんですね…  
Webサイトありがとうございます！  

コミット「list.toArray(new String[0])をlist.toArray(new String[list.size()])に変更」にて対応いたしました。

2021-05-16 09:45 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/util/SharedPreferencesUtil.java
> +        return sharedPreferences.getInt(key, SORT_MODE_DEFAULT_POSITION);
確かに後々混乱しそうなメソッド名でしたので変更させていただきました。  
コミット「SharedPreferencesUtilのメソッド名を変更」にて対応いたしました。

2021-05-16 09:45 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/DeleteDialogFragment.java
> +;
失礼しました。削除しました。

2021-05-16 09:46 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogAddFragment.java
> +    private void setDateToDivingLog(@NonNull DivingLog divingLog) {
失礼しました。修正させていただきました。

2021-05-16 15:39 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogAddFragment.java
> +    public static int getIntData(@NonNull String strData) {
コミット「ConversionUtilを作成」にて対応いたしました。  
その他Util化できるものはConversionUtilにまとめました。

2021-05-16 15:39 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogDetailFragment.java
> +    public static String createStringData(int intData) {
コミット「ConversionUtilを作成」にて対応いたしました。

2021-05-16 15:40 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogEditFragment.java
> +        parcelFileDescriptor.close();
コミット「ConversionUtilを作成」にて対応いたしました。  
Bitmapだけ分けた方がいいのでしょうか。クラスが増えてしまうと思い、型を変換するUtilクラスとしてまとめてみました。

2021-05-16 15:58 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +    public static SharedPreferencesUtil sharedPreferencesUtil;
インスタンス化する意図はありませんでしたので、インスタンス化しない方向で修正いたしました。 
コミット「SharedPreferencesUtilをインスタンス化せず使用できる様修正」にて対応いたしました。

2021-05-16 16:00 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
>      public static final String TAG = MainActivity.class.getSimpleName();
使用していません。  
間違えてpublicにしていましたのでprivateに修正いたしました。

2021-05-16 16:01 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/SortDialogFragment.java
> +public class SortDialogFragment extends DialogFragment {
失礼しました。追加しました。

2021-05-29 10:17 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/main/LogAdapter.java
> +                context.startActivity(intent);
コミット「Fragment遷移をMainActivityで行い、LogActivityを削除」にて対応いたしました。

2021-05-30 09:01 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/detail/LogEditFragment.java
> +                if ((LogAddFragment.NO_DATA == airStartInt) || (LogAddFragment.NO_DATA == airEndInt)) {
「そのintがno_dataかどうかは別のboolean変数で持つ」ということが理解できませんでしたので  
もう少し詳しく教えていただきたいです。

2021-06-21 14:25 UTC, kasai-suika commented
下記の問題についてアドバイスいただきたいです。よろしくお願いいたします。

■問題　xmlファイル名に応じたBindingクラスが生成されないこと

■現状　
　・gradleにデータ バインディングを有効にする処理を追加
　・fragment_add_log.xmlを<layout>タグでラップする処理を追加
　・ビルド実行
　・クリーンビルド、キャッシュのクリア（File -> Invalidate Caches / Restart）などの実行

■対象コミット　データバインディングクラスが生成されない

2022-01-10 14:22 UTC, merged