GPS
kasai-suika/OJT-App pull request #4
Opened 2022-01-16 16:24 UTC by kasai-suika

天気取得ボタンにGPSを活用した「現在地」を追加しました。

2022-01-18 14:49 UTC, u1tramarinet requested changes

2022-01-18 14:49 UTC, u1tramarinet commented on .idea/misc.xml
> +=======
削除してください。

2022-01-18 14:49 UTC, u1tramarinet commented on .idea/misc.xml
> +>>>>>>> d6e781740a6b513e255e78fdac5edb1b1f015a58
削除してください

2022-01-18 14:49 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +        startUpdateLocation(getApplicationContext());
93行目ではActivityContextを使用していて、ここではApplicationContextを使用しているのは何か意図ありますか？

2022-01-18 14:49 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +    public Location getLocation() {
MainActivityとMainViewModelが双方向に情報を参照しあっている状態で気になります。
データの保持はViewModelだけに任せて、ActivityはGPSから取れたものをそのままViewModelに受け流すだけ、という一方向の依存関係にできればした方がよいです

2022-01-18 14:49 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/viewModel/MainViewModel.java
> +        if (ActivityCompat.checkSelfPermission(activity, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
この処理（権限リクエスト）はMainActivity側に寄せたいですね

Void型のLiveData（≠MutableLiveData）を公開してMainActivity側でobserveするか、Listenerを新設するかをした上で、

①MainActivtyに通知する
②MainActivityでリクエスト処理をする
③MainActivityからMainViewModelへupdateの要求をする
として、極力ActivityでしかできないことだけをMainActivityでやるように意識するとすっきりすると思います。

上のようにできれば、MainViewModel上でMainActivityのWeakReferenceを持たないようにできると思います。
極力疎結合に、を意識してください。疎結合によってお互いの修正が影響し合いにくくなってやりやすくなると思います。

2022-01-18 14:49 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +        if (requestCode == 2000 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
requestCodeの値は定数で統一しておいた方がよいです。

2022-01-18 14:49 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +        if (requestCode == 2000 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
自明なのでMustではないですが、一応permissionsがACCESS_FINE_LOCATIONかは見ておいた方がいいと思います。

2022-01-18 14:49 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +            String[] permissions = {Manifest.permission.ACCESS_FINE_LOCATION};
onRequestPermissionsResultと含めてですが、Manifest.permission.ACCESS_FINE_LOCATIONは定数やfinalな配列などで管理した方がよいと思います

2022-01-18 14:49 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/constant/LogConstant.java
> +    public static final String FORMAT_WEATHER_SITE_URL_GPS = "http://api.openweathermap.org/data/2.5/weather?lat=%s&lon=%s&appid=%s";
これは好みもあるかもですが、
２つに増えたので「`http://api.openweathermap.org/data/2.5/weather?`」を別のprivateな定数で共通化して（例としてBASE_URLとする）、
「BASE_URL + "q=%s&appid=%s"」とか「BASE_URL + "lat=%s&lon=%s&appid=%s"」という風にした方が、修正もしやすいですしBaseの部分のコピペミスとかもしにくいのでお勧めだと思います。

2022-01-18 14:49 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/controller/WeatherInfoReceiver.java
> +        String urlStr = getWeatherSiteURL(params);
異なる意味を持つデータ群（「場所名」、「緯度経度」）を同じ可変数引数で扱うのは、意味を取り違えるなどしやすいと思います。
ただ、異なる意味とはいえやりたい趣旨は同じなので、下記のように同じクラスで複数の意味のデータ群を扱えるようにするとわかりよいと思います。

【例】経緯度を指定する実装をしたものの、第一数しか書いていなかった
現状：エラーは起きず実行時のエラーで初めて気づく
理想：実装時にエラーで気づき即修正できる

```
public class WeatherInfoParams {
    public static class PlaceName extends WeatherInfoParams {
        // コンストラクタの引数でPlaceNameに必要なパラメータを表現する
        public PlaceName(@NonNull String place) {
            ....
        }
    }

    public static class GeographicCoordinates extends WeatherInfoParams {
        // コンストラクタの引数でGeographicCoordinatesに必要なパラメータを表現する
         public GeographicCoordinates(@NonNull String latitude, @NonNull String longitude)) {
             ...
         }
    }
}
```

```
public class WeatherInfoReceiver extends AsyncTask<WeatherInfoParams String, String[]> {
```

```
WeatherInfoParams params = ...;

if (params instanceof WeatherInfoParams.PlaceName) {
    String place = ((WeatherInfoParams.PlaceName)params).place;
} else {
    String latitude = ((WeatherInfoParams.GeographicCoordinates)params).latitude;
    String longitude = ((WeatherInfoParams.GeographicCoordinates)params).longitude;
}

```

2022-01-18 14:49 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +    public Location getLocation() {
例えば、116行目のタイミングでviewModel側で用意するAPI経由でLocationオブジェクトを引き継ぐ

2022-01-18 14:55 UTC, u1tramarinet commented
全体として、下記を意識して今後も実装していってください。

①Activityの実装は極力Activityでしかできないことに絞って、ViewModelでもできることはViewModelにゆだねる
　→例えば、権限リクエストはActivity側でないと難しいので、Activity。Locationなどのデータの管理はViewModelへ。
②依存方向は極力一方向。今回はActivity→ViewModel。
　→相互依存は修正が難しくなりがち。ActivityをいじってもViewModelには影響しないようになる
　→将来的にModelを設ける場合はActivity（V）→ViewModel（VM）→Model（M）
③値のバリデーションを最初の段階でやる
　→APIの最初や、APIに渡すパラメータを表現するクラスで明確に定義しておけば、
　　実装中に誤りに気づきやすくなると思います。

2022-01-22 13:43 UTC, kasai-suika commented on .idea/misc.xml
> +=======
失礼しました。
コミット「不要な記載を削除」で対応しました。

2022-01-22 13:43 UTC, kasai-suika commented on .idea/misc.xml
> +>>>>>>> d6e781740a6b513e255e78fdac5edb1b1f015a58
失礼しました。
コミット「不要な記載を削除」で対応しました。

2022-01-22 13:44 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +        startUpdateLocation(getApplicationContext());
お試しで使用してそのままにしてしまっていただけなので意図的ではありません。
コミット「MainActivity内でGPS情報を保持しない」で対応しました。

2022-01-22 13:50 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +    public Location getLocation() {
コミット「MainActivity内でGPS情報を保持しない」で対応しました。

「双方向の参照」について認識が間違っていました。
（MainActivityでMainViewModelのデータを使用せず、
　MainViewModelが一方的にMainActivityの情報を見ているため一方向の参照のイメージでした。）

MainViewModelが使用する情報をMainActivityが持ってることがよくないという認識でいいのでしょうか。

2022-01-22 19:39 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/viewModel/MainViewModel.java
> +        if (ActivityCompat.checkSelfPermission(activity, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
Void型のLiveDataにできていないのですが、一旦動くコードになったため確認していただきたいです。
コミット「GPS使用のパーミッションリクエストをMainActivityで行う用に修正」で対応しました。

LiveDataはデータが変わるたびに通知が行く認識なので毎回データが変わる様にしてみました...

>MainViewModel上でMainActivityのWeakReferenceを持たないようにできると思います。

AsyncTaskやstartActivity()など決行いろいろな所でWeakReferenceを使用しますが、
こちらもActivityへの移動を考えた方がいいのでしょうか。
Activityが大きくなりすぎるなと…

2022-01-22 19:40 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +        if (requestCode == 2000 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
コミット「GPS使用のパーミッションリクエストをMainActivityで行う用に修正」で対応しました。

2022-01-22 19:40 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +            String[] permissions = {Manifest.permission.ACCESS_FINE_LOCATION};
コミット「GPS使用のパーミッションリクエストをMainActivityで行う用に修正」で対応しました。

2022-01-22 19:43 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/constant/LogConstant.java
> +    public static final String FORMAT_WEATHER_SITE_URL_GPS = "http://api.openweathermap.org/data/2.5/weather?lat=%s&lon=%s&appid=%s";
なるほどです！
コミット「BASE_URLを追加」で対応しました。

2022-01-23 17:15 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/controller/WeatherInfoReceiver.java
> +        String urlStr = getWeatherSiteURL(params);
メモ
・値設定時はnew WeatherInfoParams.PlaceName(place);で設定　ここはOK
・外部クラスWeatherInfoParamsにキャストしてAsyncTaskに渡す？エラー
・((PlaceName)params).place;　ここでもキャストしている。エラー
・"instanceof"でもエラー

2022-01-30 13:21 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/view/main/MainActivity.java
> +    public Location getLocation() {
MainViewModelの「情報を持っていること」はよくないということではないです。ここで言いたいのは、情報を持つところ、情報を操作するところは散らばらせない方がよいということです。今回の場合、極力MainViewModel側に情報の管理を任せ、MainActivityはユーザーからの操作の入口や、Activityでししかできないことに集中させた方が、①MainActivityとMainViewModelの役割が明確になり、②更新すべき情報がほぼ一か所になり、コードがスッキリしやすくなると考えているからです。

2022-02-18 14:31 UTC, u1tramarinet commented on app/src/main/java/com/ojtapp/divinglog/controller/WeatherInfoReceiver.java
> +        String urlStr = getWeatherSiteURL(params);
例に大事な継承関係書くのを忘れてました。すみません。
あくまで例なのでインナークラスかどうかはMustじゃないです...

同じまとまりのIF経由で異なるパラメータの組み合わせを扱いたい時のパターンの１つです

2022-02-27 14:05 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/controller/WeatherInfoReceiver.java
> +        String urlStr = getWeatherSiteURL(params);
なるほどです！  
 PlaceNameクラスとGeographicCoordinatesGeographicCoordinatesクラスにWeatherInfoParamsを継承するのですね。  
全然思いつきませんでした…　ありがとうございます！  
（WeatherInfoParamsクラスの中で自分を継承させることもできるのですね。不思議な感じです。）  

>同じまとまりのIF経由で異なるパラメータの組み合わせを扱いたい時のパターンの１つです

これならパラメータが少なかった際に実装段階ですぐ気づけますね。教えていただきありがとうございます。

2022-02-27 14:10 UTC, kasai-suika commented on app/src/main/java/com/ojtapp/divinglog/controller/WeatherInfoReceiver.java
> +        String urlStr = getWeatherSiteURL(params);
コミット「WeatherInfoParamsを追加」で対応しました。

2022-02-27 14:57 UTC, kasai-suika commented
これが完了したらViewModelの分担などのリファクタメインで動いていこうと思います～

2022-08-21 08:14 UTC, merged